### ISSUE TITLE
Curvepos example throws an ActorInitializationException

### ISSUE THREAD

**Issue by JohnnyKokay** [ScorexFoundation/Scorex#113]
I'm trying to run the Curvepos example with 

`sbt runMain examples.curvepos.SimpleApp`

but I keep getting the exception thrown some time after the application starts. Here's the stack trace for it:

`[info] Running (fork) examples.curvepos.SimpleApp 
[info] [main] >> [WARN ] scorex.core.settings.ScorexSettings$ >> 00:49:28.880 NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS FOR TESTNET!
[info] [scorex-akka.actor.default-dispatcher-2] >> [INFO ] scorex.core.network.UPnP >> 00:49:29.589 Looking for UPnP gateway device...
[info] [ERROR] [11/17/2017 00:49:30.023] [scorex-akka.actor.default-dispatcher-3] [akka://scorex/user/$e] assertion failed
[info] akka.actor.ActorInitializationException: akka://scorex/user/$e: exception during creation
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:607)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] Caused by: java.lang.AssertionError: assertion failed
[info] 	at scala.Predef$.assert(Predef.scala:204)
[info] 	at scala.Predef$Ensuring$.ensuring$extension2(Predef.scala:316)
[info] 	at examples.curvepos.transaction.SimpleState.$anonfun$validate$3(SimpleState.scala:115)
[info] 	at scala.collection.immutable.List.foreach(List.scala:389)
[info] 	at examples.curvepos.transaction.SimpleState.$anonfun$validate$2(SimpleState.scala:115)
[info] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info] 	at scala.util.Try$.apply(Try.scala:209)
[info] 	at examples.curvepos.transaction.SimpleState.validate(SimpleState.scala:115)
[info] 	at examples.curvepos.transaction.SimpleState.validate(SimpleState.scala:19)
[info] 	at scorex.mid.state.BoxMinimalState.applyModifier(BoxMinimalState.scala:29)
[info] 	at scorex.mid.state.BoxMinimalState.applyModifier$(BoxMinimalState.scala:28)
[info] 	at examples.curvepos.transaction.SimpleState.applyModifier(SimpleState.scala:19)
[info] 	at examples.curvepos.SimpleNodeViewHolder.genesisState(SimpleNodeViewHolder.scala:55)
[info] 	at scorex.core.NodeViewHolder.$anonfun$nodeView$1(NodeViewHolder.scala:52)
[info] 	at scala.Option.getOrElse(Option.scala:121)
[info] 	at scorex.core.NodeViewHolder.$init$(NodeViewHolder.scala:52)
[info] 	at examples.curvepos.SimpleNodeViewHolder.<init>(SimpleNodeViewHolder.scala:15)
[info] 	at examples.curvepos.SimpleApp.$anonfun$nodeViewHolderRef$1(SimpleApp.scala:32)
[info] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
[info] 	at akka.actor.Props.newActor(Props.scala:213)
[info] 	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:588)
[info] 	... 9 more`

After the exception is thrown, the app continues to run, but the only thing it does is repeatedly write this message to the console:

`[info] [INFO] [11/17/2017 00:49:30.029] [scorex-akka.actor.default-dispatcher-8] [akka://scorex/user/$e] Message [scorex.core.NodeViewHolder$Subscribe] from Actor[akka://scorex/user/$c#-1848096250] to Actor[akka://scorex/user/$e#-362370127] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

**Comment by kushti** [comment]
Finally. curvepos example is removed. TwinsCoin example is the only one included atm (also, Ergo is another example, external, any others publicly available?)
