### ISSUE TITLE
Props factory methods for all actors

### ISSUE THREAD

**Issue by daron666** [ScorexFoundation/Scorex#162]
Rework the way how we obtaining actors. According to official documentation Props factory is the best way to do it.

**Comment by EzequielPostan** [comment]
Hi @daron666,

I would like to work on this (if it is not an urgent improvement). It will help me to explore the project at the same time.
I can also suggest the creation of API definitions for each actor. 
For example, when calling the ask method we get Future[Any] as response:

val futureResult: Future[Any] = myActor ? Message

The sender of Message usually uses mapTo[A] to get a type check at runtime.

val futureResult: Future[ExpectedType] = (myActor ? Message).mapTo[ExpectedType]

This is nicer but forces the client to know what is the expected return type for the ask call.
A good approach is to create an API to interact with the actor. Example:

case class MyActorAPI(actorSystem: ActorSystem) {
  def myActor = actorSystem.actorSelection("/myActor")
  def sendMessage(): Future[ExpectedType] = {
    (myActor ? Message).mapTo[ExpectedType]
  }
}

and now the client can simply use the API as follows

def myActorAPI: MyActorAPI = MyActorAPI(actorSystem)
val futureResult: Future[ExpectedType] = myActorAPI.sendMessage()

Note that mapTo is still checked only at runtime, but now the client (user of the API) does not need to specify the expected return type.

**Comment by ceilican** [comment]
I think props factory is a good idea.

I think that a further improvement is to do what I did here:
https://gitlab.com/AxiomFlow/OuroborosPraos/blob/master/src/main/scala/ouroboros/actor/Party.scala#L195

Then you can create an actor reference without any boilerplate, as done here:
https://gitlab.com/AxiomFlow/OuroborosPraos/blob/master/src/main/scala/ouroboros/Main.scala#L37

Akka itself uses this approach for test actor refs.

**Comment by ceilican** [comment]
@EzequielPostan , as far as I know, we are not using "ask" in Scorex at the moment. We are only using "tell". So, I would put your API suggestion as low priority at the moment. And, in any case, it would be better to discuss it in a separate issue. I created an issue related to that here: https://github.com/ScorexFoundation/Scorex/issues/163 .

**Comment by daron666** [comment]
@EzequielPostan feel free to work on this.

**Comment by kushti** [comment]
I'm for using Props factory pattern. @EzequielPostan please feel free to work on this, thanks in advance! @ceilican actually we're using "ask" pattern a little bit, e.g. https://github.com/ScorexFoundation/Scorex/blob/5179a7869c67be1f6032c8537f62765dcd2d9dad/src/main/scala/scorex/core/network/NetworkController.scala#L128

**Comment by EzequielPostan** [comment]
Thanks @daron666, I will start with this.

@ceilican 
It seems that I don't have access to see the content of the links you added for further improvements. I tried to log in using Github and got a 422 error.

@kushti @ceilican 
I guess it will be better and more organized (as @ceilican mentioned) to start with the factory pattern and discuss further improvements in a separate issue.

**Comment by ceilican** [comment]
> It seems that I don't have access to see the content of the links you added for further improvements.

Those links are only accessible if are logged in GitLab. So, log in first, and then you will be able to access them.

**Comment by EzequielPostan** [comment]
That was strange, I logged in with "with Github" option and didn't work, but it now worked with normal login...

Anyway, I like the idea of MyActorRef objects to gather the factory methods, so I will refactor in this way if you agree.

**Comment by ceilican** [comment]
> Anyway, I like the idea of MyActorRef objects to gather the factory methods...

The standard approach is to have *only* the `props` factory in the `MyActor` companion object.

What I did differently was to:
1) also implement `apply` factories in an extra `MyActorRef` object, which take an actor system implicitly and then use the `props` factory.
2) move the `props` factory to `MyActorRef`, just to keep all factories close together.

I "stole" idea 1 from Akka's test-kit. They do this for `TestActorRef`. And I think this idea is very nice.

I don't have a strong opinion about 2.

**Comment by ceilican** [comment]
@EzequielPostan 
> I can also suggest the creation of API definitions for each actor.
> For example, when calling the ask method we get Future[Any] as response:

It seems that @daron666 implemented something addressing this concern of yours here: https://github.com/ScorexFoundation/Scorex/pull/164/files#diff-3550f43b428edb7b4977c425297d164eR12

**Comment by ceilican** [comment]
Coverage just fluctuated a bit because the number of lines of code that was already uncovered increased. Therefore, I think it is ok to ignore it. The problem is when coverage decreases because code that was previously covered becomes uncovered.

**Comment by EzequielPostan** [comment]
Ok, good to know.
Thanks for the review of the PR @ceilican , I left some follow up comments.

Regarding PR 164 that you mentioned, I assume you refer to this method https://github.com/ScorexFoundation/Scorex/pull/164/files#diff-3550f43b428edb7b4977c425297d164eR12

I think that in this solution, the client still has to specify the expected type. But is still nicer to read that the plain `(Actor ? Message).mapTo[Type]` expression.

**Comment by ceilican** [comment]
> Regarding PR 164 that you mentioned, I assume you refer to this method https://github.com/ScorexFoundation/Scorex/pull/164/files#diff-3550f43b428edb7b4977c425297d164eR12

Yes.

> I think that in this solution, the client still has to specify the expected type. But it is still nicer to read that the plain (Actor ? Message).mapTo[Type] expression.

Ah, I see. Indeed. Let's do one thing at a time. Let's revisit your API idea in a separate issue in the near future.
