### ISSUE TITLE
Add scalastyle report

### ISSUE THREAD

**Issue by daron666** [ScorexFoundation/Scorex#172]

**Comment by EzequielPostan** [comment]
Hi @daron666,

I can work on this one if you want help or someone to free your time.

**Comment by daron666** [comment]
@EzequielPostan Sorry, I already finished this one =)

**Comment by EzequielPostan** [comment]
hahaha, no worries  @daron666 :P

**Comment by EzequielPostan** [comment]
Hi @daron666, should this issue be closed?

**Comment by daron666** [comment]
@EzequielPostan I think so.
