### ISSUE TITLE
Wrapper for Array[Byte]

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#178]
Array[Byte] is bad as a key in maps/collections, so we anyway wrap them when use. It's better to wrap them once at object creation time. 
IODB requires ByteArrayWrapper as a key and value, may be we should wrap at least some objects (e.g. ModifierId) at object creation time

**Comment by TharinduDG** [comment]
@catena2w 
Can this be closed since the requirement changed and there's a new issue for this? 
https://github.com/ScorexFoundation/Scorex/issues/208
