### ISSUE TITLE
Remove deprecated usages of getJsonRoute

### ISSUE THREAD

**Issue by mike-aksarin** [ScorexFoundation/Scorex#182]
Remove deprecated usages of ```ApiRoute.getJsonRoute``` method from Scorex. Handle exceptions by implicit ```ExceptionHandler``` (see example at https://github.com/ergoplatform/board-new/blob/master/src/main/scala/org/ergoplatform/board/App.scala#L24). Use standard circe ```.asJson``` method from ```EncoderOps``` to convert result to Json. Add CORS header directives to the resulting routes. Handle futures in responses with ```onSuccess``` directive from ```FutureDirectives```.

**Comment by TharinduDG** [comment]
@catena2w  I think this issue can be closed.
