### ISSUE TITLE
Replace Enumerations by Case Objects

### ISSUE THREAD

**Issue by ceilican** [ScorexFoundation/Scorex#197]
Scorex has 4 Enumeration objects: `CommunicationState`, `EventType`, `ModifiersSemanticValidity` and `HistoryComparisonResult`. I think it would be more elegant to implement them with case objects instead. Like this:

Instead of:

```
  object EventType extends Enumeration {
    val Handshaked: EventType.Value = Value(1)
    val Disconnected: EventType.Value = Value(2)
  }
```

We would do:

```
sealed trait EventType
case object Handshaked extends EventType
case object Disconnected extends EventType
```

@kushti: what do you think?

**Comment by kushti** [comment]
@ceilican I agree, there're some pros of sealed traits

**Comment by EzequielPostan** [comment]
@ceilican @kushti 

This is actually the purpose of Wart Enumeration (http://www.wartremover.org/doc/warts.html)
Would you like me to take this ticket and add this wart in the process?

**Comment by ceilican** [comment]
@EzequielPostan , I have already done most of it in #203 .  There is only one enumeration remaining, but it would be useful to decide what to do with #202 before eliminating it.

**Comment by ceilican** [comment]
@EzequielPostan , if you would like to eliminate the last remaining enumeration, please go ahead. Base your PR on top of #203 . Note that there will be some name clashes when you remove that enumeration. Try to rename the clashing events sensibly.

**Comment by EzequielPostan** [comment]
@ceilican 
Ok, I will finish with the current work I have in a branch for #176 and then will check this issue.

**Comment by ceilican** [comment]
@EzequielPostan , let's put this issue on hold, because it would be in conflict with #202 .  You haven't started working on this yet, right?

**Comment by EzequielPostan** [comment]
No problem @ceilican, I haven't started yet.
