### ISSUE TITLE
Eliminate LocalInterface Actor

### ISSUE THREAD

**Issue by ceilican** [ScorexFoundation/Scorex#199]
@kushti, I think `LocalInterface` does not need to be an actor...  Currently, it seems to be just a collection of listeners for messages received mostly by `NodeViewSynchronizer`.  We could turn  `LocalInterface` into a normal non-actor class. What do you think?

This would reduce the number of messages that are passed around and would simplify the architecture.

Furthermore, the current architecture seems bug-prone, because it relies on `NodeViewHolder` sending the same messages to both `NodeViewSynchronizer` and `LocalInterface` through `notifySubscribers`... Unexpected behaviour may occur if we end up sending messages to one but not to the other...

Note also that `NodeViewSynchronizer` takes a `localInterfaceRef` as an argument, but never uses it...

It seems that the purpose of `LocalInterface` is to allow users to customize the behaviour of `NodeViewSynchronizer` and `SyncTracker`.  And this is done in a non-uniform way. In the case, of `NodeViewSynchronizer`, it is the responsibility of `NodeViewHolder` to notify `LocalInterface` that it is sending a message to `NodeViewSynchronizer`. On the other hand, in the case of `SyncTracker`, it is the `SyncTracker` itself that notifies `LocalInterface` that it received a message. This non-uniformity is unnecessarily confusing.

I think a cleaner approach would be to eliminate `LocalInterface` completely and do one of the following:

1. Make `NodeViewSynchronizer` (respectively, `SyncTracker`) extend an abstract trait containing abstract message listening methods. The user should the mix in a concrete trait providing concrete implementations for these methods when he/she instantiates the `NodeViewSynchronizer`.

2. Do essentially the same as above, but using an abstract class instead and passing an object of this class as an argument to the constructor of `NodeViewSynchronizer` (respectively, `SyncTracker`).

What do you think?

**Comment by kushti** [comment]
@ceilican I'm for that, the interface looks pretty artificial now
