### ISSUE TITLE
Hello World sample

### ISSUE THREAD

**Issue by ramnivas** [ScorexFoundation/Scorex#20]
It will really help a newcomer to get started if there is a "Hello World" level app with Scorex (something similar to slide 20 from https://www.slideshare.net/AlexChepurnoy/scorex-the-modular-blockchain-framework or https://github.com/input-output-hk/Scorex/wiki/Getting-started#running-scorex). 

I tried to port https://github.com/input-output-hk/Scorex/wiki/Getting-started#running-scorex, but there are quite a few changes between the input-output-hk version and the ScorexFoundation version, so I got lost). I am looking at examples in https://github.com/ScorexFoundation/Scorex/tree/master/examples, but there is a lot going on there, so for someone that is just starting out, it can be a bit intimidating.

**Comment by catena2w** [comment]
One of the simplest examples is here - https://github.com/ScorexFoundation/Scorex/tree/master/examples/src/main/scala/examples/curvepos

**Comment by kushti** [comment]
Unfortunately, documentation on examples is not in the tutorial (https://github.com/ScorexFoundation/ScorexTutorial) yet

**Comment by ceilican** [comment]
We have updated the examples' readme. What remains to be done, for the examples to be more understandable for newcomers, is to address issue #135 . Therefore, I'm closing this issue.

@ramnivas , if you think that anything else (apart from what is mentioned in #135) is needed, please reopen this issue and let us know.
