### ISSUE TITLE
Refactor subscription mechanism

### ISSUE THREAD

**Issue by ceilican** [ScorexFoundation/Scorex#202]
How important is the subscription pattern in Scorex?

I noticed that we frequently have the following:

* an actor `A` receives a message `M` and notifies every subscriber `S` (which subscribes to the message `M`) that an event `EventType.M` occurred.

Now in cases where `A` knows in advance who the subscriber `S` is, it would be more direct and easier to simply let `A` send a message to `S` when `A` receives `M`, instead of using the more indirect subscription mechanism.

I suppose the subscription pattern is needed because `A` doesn't always know in advance who the subscribers will be. But I don't see clearly where this is the case. @kushti, could you tell me why/where subscriptions are really needed? Could you point me to a place in Scorex's code where the more direct alternative would not work?

**Comment by daron666** [comment]
Akka has embedded message bus, that could be used for such things, btw.

**Comment by ceilican** [comment]
Thanks, @daron666 !

Here is a link to Akka's documentation about the event bus: https://doc.akka.io/docs/akka/2.5/event-bus.html

I think we should eliminate subscriptions as much as possible and use Akka's event bus in cases where subscriptions are really needed.

**Comment by kushti** [comment]
@ceilican what concrete cases do you have in your mind? Sometimes message-passing through an intermediate actor done intentionally in order not to reveal unnecessary interfaces or pass unneeded dependencies.

**Comment by ceilican** [comment]
@kushti , the issue here is not the use of intermediate actors. The issue here is the use of a complex "subscription pattern" just to achieve communication between two actors `A` and `S`, which could probably be achieved in a simpler way. For a concrete case, consider the following:

The *peer manager* (`A`) needs to tell the *node view synchronizer* (`S`) that a *handshake* (`M`) occurred. 

Right now, `S` first needs to send a message to `A` subscribing to messages of type `M`. Then later `A` sends message `M` to all subscribers, even though `S` is the **only** subscriber.

Wouldn't it be simpler to simply make `A` send `M` to `S`, without requiring `S` to subscribe first?

I see your point that, without the subscription mechanism, we would need to have an explicit dependency of `A` on `S`, but I think that in cases where there is a single subscriber, it can be an advantage to have an explicit dependency.  For example, if we look at the code of *peer manager* now, we have no idea who the subscribers are. With an explicit dependency, on the other hand, it would be clear that there is communication between the peer manager and the node view synchronizer.

Another concrete case are the events of the node view holder. Right now, there are 2 subscribers. But after the elimination of `LocalInterface`, the only subscriber will be `NodeViewSynchronizer`.

**Comment by ceilican** [comment]
In general, I think subscription mechanisms obfuscate who is communicating with whom.   I think they are justified when we have a dynamic set of actors and we don't know statically which actor is interested in receiving which message. But, when we have a fixed set of actors and we know which actor ought to receive each message, then a subscription mechanism seems to be unnecessarily indirect and obfuscating.

**Comment by kushti** [comment]
@ceilican concrete applications can add new subscribers, e.g. to update data shown in API. For examples, in Ergo there's some actor collecting statistics from the node viewable from API, and this actor is subscribing for node view updates & network events.

**Comment by ceilican** [comment]
@daron666 , I have read the documentation about event buses. There are many different ways to use event buses in akka, and I was wondering if we could reutilize the actor system's own event stream, as described in this subsection: https://doc.akka.io/docs/akka/2.5/event-bus.html#event-stream . It seems to me that this way would need the least amount of code from us. It could be the most straightforward solution. However, there is one problem that I do not know how to solve. I asked a question about it in StackOverflow (https://stackoverflow.com/questions/49334502/how-can-i-send-a-message-to-my-akka-actor-systems-event-stream-without-addressi). Do you know the answer?

**Comment by ceilican** [comment]
@kushti, after trying to eliminate `LocalInterface` (#199), I became convinced that event subscriptions are a good idea. The easiest way to eliminate `LocalInterface` is to allow applications to subscribe to events.

However, I think we need to refactor Scorex's custom subscription mechanism (which is currently duplicated in each actor that accepts subscriptions) and the best option is probably to use one of the event bus solutions provided by Akka, as suggested by @daron666 .

What do you think?  If you agree, I would first resolve this issue (#202) and only then resolve #199 .

**Comment by ceilican** [comment]
I'm renaming this issue from "Do we (always) need the "subscription" (anti-)pattern?" to "Refactor subscription mechanism".

**Comment by ceilican** [comment]
In particular, of all possible event bus solutions, I think we could use akka's own event stream instead, as explained here: https://doc.akka.io/docs/akka/2.5/event-bus.html#event-stream

@kushti, what do you think?
