### ISSUE TITLE
Is Scorex a good choice for a sidechain?

### ISSUE THREAD

**Issue by siman** [ScorexFoundation/Scorex#236]
We are writing an app that should have a high TPS (ex. 100 TPS) and periodically sync the state of a sidechain to a mainnet of an established blockchain (ex. Ethreum). For this reason, we are comparing different lightweight blockchains with PoS consensuses for the role of a sidechain in this app and we came across Scorex. 

Are there any examples of using Scorex as a sidechain? 
If yes, can you provide the links?
What about integration with popular blockchains like Bitcoin or Ethereum?

**Comment by ceilican** [comment]
> Are there any examples of using Scorex as a sidechain?

As far as I know, there are no examples for this. (@kushti, am I right?)  The main example that we provide and maintain is Twinscoin (https://github.com/ScorexFoundation/Scorex/tree/master/examples).

> What about integration with popular blockchains like Bitcoin or Ethereum?

Also, no example for this to the best of my knowledge. But nothing prevents you from implementing your own integration. Scorex provides abstractions to help you implement your own blockchain. If you would like to allow your blockchain to communicate with Bitcoin's blockchain or Ethereum's blockchain, it is your responsibility to implement a component inside your Scorex application that would interact with a Bitcoin node or an Ethereum node/app and post data of your blockchain to Bitcoin's blockchain or Ethereum's blockchain.

**Comment by siman** [comment]
Thank you!
