### ISSUE TITLE
Add support for peer features

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/Scorex#272]
This ticket is proposing to add abstract peer "features" to be advertised during handshaking.
A list of peer features (or capabilities) contains static characteristics of a running node. As an example, "services" bitfield announced in during handshaking in the Bitcoin networking protocol ("https://en.bitcoin.it/wiki/Protocol_documentation#version") shows services supported by a peer (e.g. whether it can serve peers around with full blocks or UTXO lookups etc). As another example, a feature can list supported protocols for encryption.     

A feature is rather abstract interface, from Scorex core we require from a feature to be (de)serializable, and we require an Application trait implementation to define a concrete instantiation of peer features (to be then serialized and sent other wire to another peer).

**Comment by catena2w** [comment]
closed in https://github.com/ScorexFoundation/Scorex/pull/273
