### ISSUE TITLE
Peer discovery

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#296]
We wrote a test for peers discovery (issue https://github.com/ergoplatform/ergo/issues/253, PR https://github.com/ergoplatform/ergo/pull/371), and looks like peer discovery does not work - if there is a connection betweern nodes 1-2 and 1-3, connection between nodes 2-3 is not created.
Can be reproduced in Scorex by running 3 nodes of `examples/src/main/scala/examples/hybrid/HybridApp.scala` with configs: 
```
examples/src/main/resources/settings.conf
examples/src/main/resources/settings2.conf
examples/src/main/resources/settings3.conf
```

**Comment by catena2w** [comment]
@ceilican @VictorMikheev may you add some comments?

**Comment by ceilican** [comment]
@catena2w , it looks like @VictorMikheev already solved the issue. If you still need comments from me, let me know. I'm a bit overloaded with tasks from IOHK at the moment...
