### ISSUE TITLE
Priorities / roadmap / community chat?

### ISSUE THREAD

**Issue by RatanRSur** [ScorexFoundation/Scorex#300]
Hi! I started implementing my own cryptocurrency as a fun personal project in Scala and realized I was doing so much of the same stuff as y'all.

https://github.com/RatanRSur/raicoin/tree/tcp-networking

I have a lot of free time on my hands right now being in between jobs so I was wondering if you had a roadmap of Scorex's future or a chat where you discuss them.

I took a look at the issues but it's unclear which are major priorities and which are just nice-to-haves. It's understandable because you're likely using them to track issues for yourself/between team members but a bit opaque from the outside.

Thanks and excited to contribute!

**Comment by ceilican** [comment]
@RatanRSur , unfortunately there is no public roadmap. Currently, networking is being improved and being made more robust for the next release. The priorities for Scorex also depend a lot on the needs of projects that use it, such as Ergo.

I imagine that, if you would like to contribute, maybe the best approach is to have a look on the issue tracker and ask, on a particular issue, whether you could contribute to solving that issue.
