### ISSUE TITLE
Scorex testkit Hybrid example missing

### ISSUE THREAD

**Issue by deabreu** [ScorexFoundation/Scorex#353]
Hi, MD page for testkit has a missing link for Hybrid Example. I got a 404 Response.

**Comment by kushti** [comment]
Thanks! PR with the proper link (https://github.com/ScorexFoundation/Scorex/blob/master/examples/src/test/scala/hybrid/HybridSanity.scala) is ready!

**Comment by deabreu** [comment]
Thanks!
