### ISSUE TITLE
Scorex RC6 dependency issue

### ISSUE THREAD

**Issue by i-Alex** [ScorexFoundation/Scorex#360]
In maven repository Scorex 2.0.0-RC6 has a problem with `io.circe.circe-core` dependency, that was not present in RC4.
In Scorex build.sbt file version `0.8.0` was set, but actually Scorex is built with `0.9.x` version.
I suppose, that it's because of `"de.heikoseeberger" %% "akka-http-circe" % "1.20.0"`, that as a subdependency has `io.circe.circe-core 0.9.x`.

Here is the screen of RC6 dependencies on my machine:
![scorex-rc6-circe-problem](https://user-images.githubusercontent.com/3390270/73348095-7216a800-4291-11ea-8713-7aef81cd016a.png)

Actually problem occurs when I use Scorex RC6 maven dependency in my project. Each time when `ApiRoute` class initialization is processed, I have an exception of non-existing method for `implicit val printer: Printer = Printer.spaces2.copy(dropNullValues = true)`, because `io.circe.Printer` trait is different in circe `0.8.x` and `0.9.x`. 

**Solution**: update `build.sbt` with
`val circeVersion = "0.9.0"` or even newer.

**Comment by kushti** [comment]
@i-Alex thank for reporting! I've created #361 with the dependency update proposed
