### ISSUE TITLE
Remember time of last seen message

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/Scorex#374]
Do this on top of PR #373 :

1) Like #373 is using message got from a peer to drop inactive connection (in NetworkController), introduce global variable in NetworkController which is storing when we got last message from the network

2) Introduce a new API method /peers/status (PeersApiRoute) which is returning something like {"lastIncomingMessage":XXX, "currentNetworkTime":XXX}

**Comment by knizhnik** [comment]
I have several questions:
1. Should we maintain lastIcommingMessageTimestamp separately for each peer or just one for all peers? In first case I do not understand how it can be global variable in NetworkController. May be we should add this field to PeerInfo (in addition to lastSeen) or to ConnectedPeer ? 
2. Should I introduce new response schema PeerStatus or just add lastIncomingMessage field to existed Peer schema?
It the last case - do we need new /peers/status  method at all? We can get this information using peers/all and peers/connected requests. If we really need separate /peers/status  method  - should it return info for all peers or just connected peers?
3. As far as I understand /peers/status should return status of multiple peers. If so, why do we need to repeat  "currentNetworkTime" for all of them? Current node time can be obtained using /info method  (NodeInfo.currentTime)

**Comment by kushti** [comment]
@knizhnik  My bad likely, it was better to start with motivation. Which is about the need to recognize whether connectivity globally (with all the peers) is lost or not. If it lost, then we can consider our syncing status differently, show warning in a UI etc. 

Thus this variable is global for all the peers. 

/info is not in Scorex, it is Scorex-specific. In Ergo, we can enrich /info for sure.

**Comment by knizhnik** [comment]
Sorry, I do not understand your answers.
My first questions was why do we need to add some global variable to NetworkController insteadof just calculating max(lastSeen) ?

Also I do not understand "/info is not in Scorex, it is Scorex-specific".
All API methods are declared in openapi.yaml aren't them?
No AI methods are defined in Scorex, aren't them?
So, as far as I understand this task requires patching both "scorex" and "ergo" projects.

**Comment by knizhnik** [comment]
I have created PR https://github.com/ScorexFoundation/Scorex/pull/376
Not sure that it is enough and whether openapi.yaml in ergo should also be changed.

**Comment by kushti** [comment]
Done in #376
