### ISSUE TITLE
Examples' README.md needs to be updated

### ISSUE THREAD

**Issue by ceilican** [ScorexFoundation/Scorex#54]
The [Examples's README.md](https://github.com/ScorexFoundation/Scorex/blob/master/examples/README.md) needs to be updated to Scorex 2.0.  At the end of the README, the user is told to use `cli.sh`, but Scorex 2.0 doesn't have a `cli.sh` anymore.

**Comment by ceilican** [comment]
By the way, I tried to use the `cli.sh` from the [previous version](https://github.com/input-output-hk/Scorex/blob/master/cli.sh) (modifying the jar filename and the package of ApiClient, of course), but I had some difficulties. When I sent the POST command as instructed in the README, I got the following error message:

```
[POST payment {"amount":400, "fee":1, "sender":"2kx3DyWJpYYfLErWpRMLHwkL1ZGyKHAPNKr", "recipient":"Y2BXLjiAhPUMSo8iBbDEhv81VwKnytTXsH"} RESULT] Problem occurred java.net.ConnectException: Connection refused! 
 Type help to get a list of commands.
```

I tried this with two different settings:

1. two `HybridApp` nodes (running with "settings.json" and "settings2.json") and the `ApiClient` running with "settings3.json".

2. just the `ApiClient`, running with "settings.json".

In both cases I got the same error above.

Am I doing something wrong?

(P.S. I did verify that my firewall is off and not blocking any connection.)

**Comment by ceilican** [comment]
In the second case (i.e. just the `ApiClient`, running with "settings.json"), I would expect a better error message, saying that there is no server.

**Comment by ceilican** [comment]
I also noticed that `ApiClient` has a hard-coded URL address pointing to 127.0.0.1, instead of getting the address from JSON settings. Is this intended?

**Comment by Fetiorin** [comment]
Any updates on README?

I just tried to run `ApiClient` via sbt and the best result was error below

```
[info] Welcome to the Scorex command-line client...
[error] Exception in thread "main" java.lang.NullPointerException
```

when trying to run it in sbt like this `run-main scorex.core.api.client.ApiClient settings3.json`

**Comment by ceilican** [comment]
This issue has been closed yesterday in this commit: https://github.com/ScorexFoundation/Scorex/commit/bb36767 .

**Comment by ceilican** [comment]
Actually, there were still some issues in the README after that commit. I submitted a Pull Request (https://github.com/ScorexFoundation/Scorex/pull/67) fixing them.
