### ISSUE TITLE
Node view synchronizer refactoring

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/Scorex#75]
NodeViewSynchronizer is caching ids of modifiers (blocks/transactions etc) asked from network (so only objects requested are expected to be delivered):
  private val asked = mutable.Map[ModifierTypeId, mutable.Set[ModifierId]]()

However, this structure is not storing a peer being asked.

Also, we need to have another structure which contains objects delivered, in order to extract a peer when, during processing, a node is realizing that object sent is e.g. invalid (so the peer is to be banned or de-prioritized)

  private val delivered = mutable.Map[ModifierId, ConnectedPeer]()

**Comment by AxiomFlow** [comment]
@kushti , maybe this issue can be closed?
