### ISSUE TITLE
ApiClient Json parsing error

### ISSUE THREAD

**Issue by AlanVerbner** [ScorexFoundation/Scorex#8]
### Description

After downloading and running one of the example projects when trying to query REST api using the provided ApiClient we are receiving an error while parsing Json response.

### Error Output

```
[info] Welcome to the Scorex command-line client...
GET utils/seed
[info] [GET utils/seed RESULT] Problem occurred java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {; line: 1, column: 0])
[info]  at [Source: {; line: 1, column: 3]! 
```

### How to reproduce
1. Startup any of the examplel projects included in this repo, for example, `SimpleApp.scala`
2. Run ApiClient
3. Execute the command `GET utils/seed`

### Cause

It seems that `scorex.core.api.http.ApiRoute#jsonRoute` calls Json.toString which uses by default [spaces2 formatting](https://github.com/travisbrown/circe/blob/b0ccd3b44706c5c51041675e0b68cc7ad3b3bd0f/modules/core/shared/src/main/scala/io/circe/Json.scala#L150) and returns a multi line string but ApiClient is expecting a [single one](https://github.com/ScorexFoundation/Scorex/blob/68428467e251b1cc8b5fa884ae931c20ba5b8a32/src/main/scala/scorex/core/api/client/ApiClient.scala#L47)

```
scala> foo.asJson.noSpaces
res0: String = {"Qux":{"i":13,"d":14.0}}

scala> foo.asJson.spaces2
res1: String =
{
  "Qux" : {
    "i" : 13,
    "d" : 14.0
  }
}

scala> foo.asJson.toString
res3: String =
{
  "Qux" : {
    "i" : 13,
    "d" : 14.0
  }
}

```

### How to Fix
There are two options:
1. Change ApiRoute in order to return Json encoded with noSpaces (this might be the best alternative because formatting is not needed before sending to the wire)
2. Change ApiClient to receive multiline Strings, `val result = Source.fromInputStream(stream) mkString ""`

We can create a PR if you want to.

**Comment by kushti** [comment]
Thanks for reporting! Fixed with `val result = Source.fromInputStream(stream).mkString("")`
