### ISSUE TITLE
NodeViewHolder modifiersCache

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#88]
If some invalid modifiers appear in modifiersCache, they'll live there forever. 

- [ ] Clear old modifier by some condition
- [ ] Limit  modifiersCache size
- [ ] Do not show all ids list in logs (which is huge if cache size ~40000)

**Comment by Tolsi** [comment]
Looks like that is work for Guava LRU Cache!

**Comment by daron666** [comment]
Another LRU/TTL caches from twitter https://github.com/twitter/storehaus/wiki/Storehaus-Cache

**Comment by TharinduDG** [comment]
@kushti shall I start working on this issue with `Storehaus-Cache`?

**Comment by catena2w** [comment]
fixed in https://github.com/ScorexFoundation/Scorex/pull/262
